# Generated by Django 5.0.14 on 2026-07-29 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_group_alter_conversation_id_alter_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='last_read_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
