# Generated by Django 5.0.14 on 2026-07-30 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_call'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='favourited_by',
            field=models.ManyToManyField(blank=True, related_name='favourited_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, related_name='pinned_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='favourited_by',
            field=models.ManyToManyField(blank=True, related_name='favourited_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, related_name='pinned_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
