# Generated by Django 5.0.14 on 2026-07-31 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_conversation_deleted_by_conversation_muted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='archived_by',
            field=models.ManyToManyField(blank=True, related_name='archived_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='archived_by',
            field=models.ManyToManyField(blank=True, related_name='archived_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
