# Generated by Django 5.0.14 on 2026-08-04 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_pollvote_pollvote_unique_poll_vote_dm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='status_files/')),
                ('bg_color', models.CharField(default='#0b141a', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='StatusView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='chat.status')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-viewed_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='statusview',
            constraint=models.UniqueConstraint(fields=('status', 'viewer'), name='unique_status_view'),
        ),
    ]
