# Generated by Django 5.0.14 on 2026-08-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_status_statusview_statusview_unique_status_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
