# Generated by Django 5.0.14 on 2026-08-06 04:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_status_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='disappearing_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='disappearing_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_group_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
